[packages]

[packages.darwin]
brew = [
  "btop",
  "fd",
  "fzf",
  "git",
  "gpg",
  "httpie",
  "lazygit",
  "nvim",
  "starship",
  "treemd",
  "treesitter",
  "treesitter-cli",
  "zoxide",
  "zsh"
]
cask = [
  "firefox",
  "font-jetbrains-mono-nerd-font",
  "font-zed-mono-nerd-font",
  "ghostty",
  "google-chrome",
  "linearmouse",
  "raycast",
  "visual-studio-code",
  "whatsapp",
]

[packages.linux]
apt = [
  "git",
  "zsh"
]

[packages.mise]
github-cli = "latest"
uv = "latest"

[packages.npm]

[packages.others]
