format = "$character"
right_format = "$directory$git_branch$username$time$hostname"

add_newline = true

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
format = ' [\($branch(:$remote_branch)\)]($style)'

[hostname]
format = ' 🌐'
ssh_only = false
detect_env_vars = ['DEVPOD', 'CODESPACES']

[time]
format = ' \[[$time]($style)\]'
disabled = false

[username]
format = ' \[[$user]($style)'
show_always = false
