format = "$character"
right_format = "$directory$git_branch$username$hostname$time"

add_newline = true

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
format = ' [\($branch(:$remote_branch)\)]($style)'

[hostname]
format = '[@$ssh_symbol$hostname]($style)\]'
ssh_only = true

[time]
format = ' \[[$time]($style)\]'
disabled = false

[username]
format = ' \[[$user]($style)'
show_always = false
